services:
  warc-gpt:
    container_name: warc-gpt
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      OLLAMA_API_URL: ${OLLAMA_API_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
      WARC_FOLDER_PATH: ${WARC_FOLDER_PATH}
      VISUALIZATIONS_FOLDER_PATH: ${VISUALIZATIONS_FOLDER_PATH}
      VECTOR_SEARCH_PATH: ${VECTOR_SEARCH_PATH}
    volumes:
      - "${WARC_FOLDER_PATH}:/warc"
      - "${VECTOR_SEARCH_PATH}:/chromadb"
      - "${VISUALIZATIONS_FOLDER_PATH}:/visualizations"